import os

API_ID = os.environ.get('API_ID')
API_HASH = os.environ.get('API_HASH')

ACCOUNTS_FILENAME = 'accounts.csv'
LINKS_FILENAME = 'links.csv'

IMAGES_DIRECTORY_NAME = 'images'
ALLOWED_IMAGES_EXTENSIONS = ['jpg', 'jpeg', 'png']

ASYA_TG_ID = 1593215207
DIMA_TG_ID = 658720016
CHAT_BOT_TG_ID = 1808403369

CHAT_BOT_MESSAGES_TIMEOUT = 15

PROXY_HOST = 'bproxy.site'
PROXY_PORT = 10749
PROXY_LOGIN = os.getenv('PROXY_LOGIN')
PROXY_PASSWORD = os.getenv('PROXY_PASSWORD')
